name: Java CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Create data directory
        run: mkdir -p data && touch data/test-drivers.txt data/integration-drivers.txt
      - name: Run tests
        run: mvn test
